export const departmentsWithTeams = {
  Districts: [
    "Anagkazo Community",
    "Bethel Community",
    "Dominion Kingdom Community",
    "Gbagada Estate Community",
    "Harmony Community",
    "Hephzibah Community",
    "Lightbearers Community",
    "Ogudu/Alapere Community",
    "Praise (Couple) Community",
    "Rehoboth Community",
    "Royal Priesthoods Community",
    "Shekinah Community",
    "Shomolu 2 Community",
    "Sunrise Community",
    "Trailblazer Community",
  ],
  "General Service": [
    "Admin and Facility",
    "Communications (DMU)",
    "Finance",
  ],
  "Interactive Groups": [
    "Men of Harvest",
    "Singles Ministry",
    "Women of Wisdom",
  ],
  Maturity: [
    "Courses HSDC",
    "Discipleship Event",
    "Group Partnership",
    "Prayer and Bible Study",
  ],
  Membership: [
    "Benevolence",
    "Call Center",
    "Celebration",
    "Ceremonies",
    "Data Management",
    "Growth Track",
    "Guest Welcome",
    "Info Hub",
    "Interactors",
    "Membership Admin",
    "New Convert",
    "Sub team heads Membership",
    "Weddings",
  ],
  Ministry: [
    "Call Centre",
    "Career and Finance",
    "Discipleship, Bible Study and Prayer",
    "Elders Care",
    "Kids Support",
    "Leadership Effectiveness",
    "Leadership Recruitment",
    "Leadership Training",
    "Legal Aid",
    "Medical Ministry",
    "Ministry team leadership",
    "Pastoral Care",
    "Prison Ministry",
    "Recruitment and Assimilation",
    "Workforce Admin",
  ],
  Mission: [
    "Evangelism",
    "God's encounter",
    "HSAP",
    "Invest and Invite",
    "Publicity",
    "Sub team-Missions",
    "Target Missions",
  ],
  NLP: ["NLP"],
  "Next Gen": [
    "Administration - Kidszone",
    "Administration - Stirhouse",
    "Learning and Development - Kidszone",
    "Learning and Development - Stirhouse",
    "Programming and Environment - Kidszone",
    "Programming and Environment - Stirhouse",
    "Reach and Partnership - Kidszone",
    "Reach and Partnership - Stirhouse",
  ],
  Programs: [
    "Diamond ET",
    "Emerald ET",
    "Pearl ET",
    "Sapphire ET",
    "Musicians",
    "Greeters - Team Jireh",
    "Greeters - Team Nissi",
    "Greeters - Team Rapha",
    "Greeters - Team Yahweh",
    "Harvesters Intelligence Unit",
    "Media-Administration",
    "Media-Audio Production",
    "Media-Equipment Management",
    "Media-Experience",
    "Media-Light",
    "Media-Livestream",
    "Media-Photo (Capturing)",
    "Media-Text & Timing",
    "Media-Video",
    "Media-Visuals",
    "Program Management",
    "Programs Admin Team",
    "Protocol",
    "Quality Assurance",
    "Sound",
    "Traffic",
    "Unveil",
    "Ushering - Bimpe",
    "Ushering - Iyaanu",
    "Ushering - Kofoworola",
    "Ushering - Queen",
    "Ushering - Tosin",
    "Venue Management - Boluwatife team",
    "Venue Management - Emmanuel team",
    "Venue Management - Feyisayo Phillip team",
    "Venue Management - Tosin Agbetuyi team",
    "Venue Management - Zeina team",
  ],
  "Senior Leadership": [
    "Directional leader",
    "Pastoral Leaders",
  ],
};

export const teamsSummary = [
  {
    label: "All Teams",
    value: "All",
  },
  {
    label: "Districts",
    value: "Districts",
  },
  {
    label: "General Service",
    value: "General Service",
  },
  {
    label: "Interactive Groups",
    value: "Interactive Groups",
  },
  {
    label: "Maturity",
    value: "Maturity",
  },
  {
    label: "Membership",
    value: "Membership",
  },
  {
    label: "Ministry",
    value: "Ministry",
  },
  {
    label: "Mission",
    value: "Mission",
  },
  {
    label: "NLP",
    value: "NLP",
  },
  {
    label: "Next Gen",
    value: "Next Gen",
  },
  {
    label: "Programs",
    value: "Programs",
  },
  {
    label: "Senior Leadership",
    value: "Senior Leadership",
  },
];